- name: "build files"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: "run migrations"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run migrations > migrations.txt
    cat migrations.txt

- name: "use pm2 to run the node server"
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run "start:dev"
